version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password  # Change this to your desired password
      POSTGRES_DB: cloudlocker_db
    ports:
      - "5500:5432"
